"""add_campus_table_and_relationships

Revision ID: 12be2d72ba43
Revises: b2c3d4e5f6a7
Create Date: 2025-11-20 05:21:47.365613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12be2d72ba43'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rto_profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rto_profile_id'], ['rto_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_rto_profile_id'), 'campus', ['rto_profile_id'], unique=False)
    op.drop_index('ix_timeline_entry_application_id', table_name='comment')
    op.drop_index('ix_timeline_entry_created_at', table_name='comment')
    op.create_index(op.f('ix_comment_application_id'), 'comment', ['application_id'], unique=False)
    op.create_index(op.f('ix_comment_created_at'), 'comment', ['created_at'], unique=False)
    op.add_column('course_offering', sa.Column('campus_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_course_offering_campus_id'), 'course_offering', ['campus_id'], unique=False)
    op.create_foreign_key(None, 'course_offering', 'campus', ['campus_id'], ['id'], ondelete='SET NULL')
    op.drop_column('course_offering', 'campus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_offering', sa.Column('campus', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'course_offering', type_='foreignkey')
    op.drop_index(op.f('ix_course_offering_campus_id'), table_name='course_offering')
    op.drop_column('course_offering', 'campus_id')
    op.drop_index(op.f('ix_comment_created_at'), table_name='comment')
    op.drop_index(op.f('ix_comment_application_id'), table_name='comment')
    op.create_index('ix_timeline_entry_created_at', 'comment', ['created_at'], unique=False)
    op.create_index('ix_timeline_entry_application_id', 'comment', ['application_id'], unique=False)
    op.drop_index(op.f('ix_campus_rto_profile_id'), table_name='campus')
    op.drop_table('campus')
    # ### end Alembic commands ###
