"""Initial v3.1 schema with 16 tables

Revision ID: 1205e3db7232
Revises: 
Create Date: 2025-11-14 05:55:15.015650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1205e3db7232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_offering',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('intake', sa.String(length=50), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('tuition_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_offering_course_code'), 'course_offering', ['course_code'], unique=True)
    op.create_table('document_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.Enum('DRAFT', 'SUBMITTED', 'STAFF_REVIEW', 'AWAITING_DOCUMENTS', 'GS_ASSESSMENT', 'OFFER_GENERATED', 'OFFER_ACCEPTED', 'ENROLLED', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('ocr_model_ref', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_type_code'), 'document_type', ['code'], unique=True)
    op.create_table('rto_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abn', sa.String(length=20), nullable=True),
    sa.Column('cricos_code', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('brand_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('business_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'AGENT', 'STAFF', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('rto_profile_id', sa.UUID(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('admin_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rto_profile_id'], ['rto_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_rto_profile_id'), 'user_account', ['rto_profile_id'], unique=False)
    op.create_table('agent_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_account_id', sa.UUID(), nullable=False),
    sa.Column('agency_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_account_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_payload', 'audit_log', ['payload_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('staff_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_account_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_account_id')
    )
    op.create_table('student_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_account_id', sa.UUID(), nullable=False),
    sa.Column('given_name', sa.String(length=100), nullable=False),
    sa.Column('family_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('visa_type', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_account_id')
    )
    op.create_table('application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('agent_profile_id', sa.UUID(), nullable=True),
    sa.Column('course_offering_id', sa.UUID(), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('current_stage', sa.Enum('DRAFT', 'SUBMITTED', 'STAFF_REVIEW', 'AWAITING_DOCUMENTS', 'GS_ASSESSMENT', 'OFFER_GENERATED', 'OFFER_ACCEPTED', 'ENROLLED', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('decision_at', sa.DateTime(), nullable=True),
    sa.Column('usi', sa.String(length=20), nullable=True),
    sa.Column('usi_verified', sa.Boolean(), nullable=False),
    sa.Column('usi_verified_at', sa.DateTime(), nullable=True),
    sa.Column('enrollment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emergency_contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health_cover_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disability_support', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language_cultural_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('survey_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gs_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('form_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_profile_id'], ['agent_profile.id'], ),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff_profile.id'], ),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offering.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_application_disability', 'application', ['disability_support'], unique=False, postgresql_using='gin')
    op.create_index('idx_application_emergency', 'application', ['emergency_contacts'], unique=False, postgresql_using='gin')
    op.create_index('idx_application_enrollment', 'application', ['enrollment_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_application_gs_assessment', 'application', ['gs_assessment'], unique=False, postgresql_using='gin')
    op.create_index('idx_application_health_cover', 'application', ['health_cover_policy'], unique=False, postgresql_using='gin')
    op.create_index('idx_application_language', 'application', ['language_cultural_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_application_services', 'application', ['additional_services'], unique=False, postgresql_using='gin')
    op.create_index('idx_application_signatures', 'application', ['signature_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_application_survey', 'application', ['survey_responses'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_application_agent_profile_id'), 'application', ['agent_profile_id'], unique=False)
    op.create_index(op.f('ix_application_assigned_staff_id'), 'application', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_application_course_offering_id'), 'application', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_application_current_stage'), 'application', ['current_stage'], unique=False)
    op.create_index(op.f('ix_application_student_profile_id'), 'application', ['student_profile_id'], unique=False)
    op.create_table('application_stage_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.Enum('DRAFT', 'SUBMITTED', 'STAFF_REVIEW', 'AWAITING_DOCUMENTS', 'GS_ASSESSMENT', 'OFFER_GENERATED', 'OFFER_ACCEPTED', 'ENROLLED', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=True),
    sa.Column('to_stage', sa.Enum('DRAFT', 'SUBMITTED', 'STAFF_REVIEW', 'AWAITING_DOCUMENTS', 'GS_ASSESSMENT', 'OFFER_GENERATED', 'OFFER_ACCEPTED', 'ENROLLED', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_stage_history_application_id'), 'application_stage_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_stage_history_changed_at'), 'application_stage_history', ['changed_at'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED', name='documentstatus'), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('ocr_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ocrstatus'), nullable=False),
    sa.Column('ocr_completed_at', sa.DateTime(), nullable=True),
    sa.Column('gs_document_requests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_type.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_gs_requests', 'document', ['gs_document_requests'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_application_id'), 'document', ['application_id'], unique=False)
    op.create_index(op.f('ix_document_document_type_id'), 'document', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_document_status'), 'document', ['status'], unique=False)
    op.create_index(op.f('ix_document_uploaded_at'), 'document', ['uploaded_at'], unique=False)
    op.create_table('employment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('employer', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_history_application_id'), 'employment_history', ['application_id'], unique=False)
    op.create_table('qualification_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('qualification_name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualification_history_application_id'), 'qualification_history', ['application_id'], unique=False)
    op.create_table('schooling_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('qualification_level', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schooling_history_application_id'), 'schooling_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_schooling_history_country'), 'schooling_history', ['country'], unique=False)
    op.create_table('document_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('blob_url', sa.String(length=1000), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('ocr_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preview_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_version_document_id'), 'document_version', ['document_id'], unique=False)
    op.create_table('timeline_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('APPLICATION_CREATED', 'STAGE_CHANGED', 'DOCUMENT_UPLOADED', 'DOCUMENT_VERIFIED', 'COMMENT_ADDED', 'ASSIGNED', 'EMAIL_SENT', 'SYSTEM_EVENT', name='timelineentrytype'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.Enum('STUDENT', 'AGENT', 'STAFF', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stage', sa.Enum('DRAFT', 'SUBMITTED', 'STAFF_REVIEW', 'AWAITING_DOCUMENTS', 'GS_ASSESSMENT', 'OFFER_GENERATED', 'OFFER_ACCEPTED', 'ENROLLED', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=True),
    sa.Column('linked_document_id', sa.UUID(), nullable=True),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['linked_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_timeline_event_payload', 'timeline_entry', ['event_payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_timeline_entry_application_id'), 'timeline_entry', ['application_id'], unique=False)
    op.create_index(op.f('ix_timeline_entry_correlation_id'), 'timeline_entry', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_timeline_entry_created_at'), 'timeline_entry', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_entry_created_at'), table_name='timeline_entry')
    op.drop_index(op.f('ix_timeline_entry_correlation_id'), table_name='timeline_entry')
    op.drop_index(op.f('ix_timeline_entry_application_id'), table_name='timeline_entry')
    op.drop_index('idx_timeline_event_payload', table_name='timeline_entry', postgresql_using='gin')
    op.drop_table('timeline_entry')
    op.drop_index(op.f('ix_document_version_document_id'), table_name='document_version')
    op.drop_table('document_version')
    op.drop_index(op.f('ix_schooling_history_country'), table_name='schooling_history')
    op.drop_index(op.f('ix_schooling_history_application_id'), table_name='schooling_history')
    op.drop_table('schooling_history')
    op.drop_index(op.f('ix_qualification_history_application_id'), table_name='qualification_history')
    op.drop_table('qualification_history')
    op.drop_index(op.f('ix_employment_history_application_id'), table_name='employment_history')
    op.drop_table('employment_history')
    op.drop_index(op.f('ix_document_uploaded_at'), table_name='document')
    op.drop_index(op.f('ix_document_status'), table_name='document')
    op.drop_index(op.f('ix_document_document_type_id'), table_name='document')
    op.drop_index(op.f('ix_document_application_id'), table_name='document')
    op.drop_index('idx_document_gs_requests', table_name='document', postgresql_using='gin')
    op.drop_table('document')
    op.drop_index(op.f('ix_application_stage_history_changed_at'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_application_id'), table_name='application_stage_history')
    op.drop_table('application_stage_history')
    op.drop_index(op.f('ix_application_student_profile_id'), table_name='application')
    op.drop_index(op.f('ix_application_current_stage'), table_name='application')
    op.drop_index(op.f('ix_application_course_offering_id'), table_name='application')
    op.drop_index(op.f('ix_application_assigned_staff_id'), table_name='application')
    op.drop_index(op.f('ix_application_agent_profile_id'), table_name='application')
    op.drop_index('idx_application_survey', table_name='application', postgresql_using='gin')
    op.drop_index('idx_application_signatures', table_name='application', postgresql_using='gin')
    op.drop_index('idx_application_services', table_name='application', postgresql_using='gin')
    op.drop_index('idx_application_language', table_name='application', postgresql_using='gin')
    op.drop_index('idx_application_health_cover', table_name='application', postgresql_using='gin')
    op.drop_index('idx_application_gs_assessment', table_name='application', postgresql_using='gin')
    op.drop_index('idx_application_enrollment', table_name='application', postgresql_using='gin')
    op.drop_index('idx_application_emergency', table_name='application', postgresql_using='gin')
    op.drop_index('idx_application_disability', table_name='application', postgresql_using='gin')
    op.drop_table('application')
    op.drop_table('student_profile')
    op.drop_table('staff_profile')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index('idx_audit_payload', table_name='audit_log', postgresql_using='gin')
    op.drop_table('audit_log')
    op.drop_table('agent_profile')
    op.drop_index(op.f('ix_user_account_rto_profile_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('rto_profile')
    op.drop_index(op.f('ix_document_type_code'), table_name='document_type')
    op.drop_table('document_type')
    op.drop_index(op.f('ix_course_offering_course_code'), table_name='course_offering')
    op.drop_table('course_offering')
    # ### end Alembic commands ###
